resources:
- release-service-account-rb.yaml
- persistent-volume-claim.yaml
- release-pipeline-sa.yaml
- remote-secrets
- release-pipeline-sign-sa.yaml
- release-service-account-sign-rb.yaml
- terraform-provider-rpa.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: managed-release-team-tenant
