apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: managed-release-team-tenant-release-service-sign-pipeline-rolebinding-managed
  namespace: managed-release-team-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: rh-sign-and-push-to-github
    namespace: managed-release-team-tenant
