---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: terraform-provider-rhcs-rhtap
  namespace: dev-release-team-tenant
spec:
  application: terraform-provider-rhcs-rhtap
  target: managed-release-team-tenant
